(1 ponto) Write Python code from scratch to find error metrics of deep learning model. Actual
values and deep learning model predicted values are shown in Table 1. Also compare the results
with the outcomes of libraries
YActual YP red
20 20.5
30 30.3
40 40.2
50 50.6
60 60.7
Tabela 1: YActual Vs. YP red

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
YActual = np.array([20, 30, 40, 50, 60])
YPred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])
MAE = np.mean(np.abs(YActual - YPred))
MSE = np.mean((YActual - YPred) ** 2)
RMSE = np.sqrt(MSE)
SS_total = np.sum((YActual - np.mean(YActual)) ** 2)
SS_residual = np.sum((YActual - YPred) ** 2)
R2 = 1 - (SS_residual / SS_total)
print(f"Manual Error Metrics:")
print(f"Mean Absolute Error (MAE): {MAE}")
print(f"Mean Squared Error (MSE): {MSE}")
print(f"Root Mean Squared Error (RMSE): {RMSE}")
print(f"R-squared (R²): {R2}")


Manual Error Metrics:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127
R-squared (R²): 0.99877


In [ ]:
MAE_sklearn = mean_absolute_error(YActual, YPred)
MSE_sklearn = mean_squared_error(YActual, YPred)
RMSE_sklearn = np.sqrt(MSE_sklearn)
R2_sklearn = r2_score(YActual, YPred)
print("\nSklearn Error Metrics:")
print(f"Mean Absolute Error (MAE) using sklearn: {MAE_sklearn}")
print(f"Mean Squared Error (MSE) using sklearn: {MSE_sklearn}")
print(f"Root Mean Squared Error (RMSE) using sklearn: {RMSE_sklearn}")
print(f"R-squared (R²) using sklearn: {R2_sklearn}")



Sklearn Error Metrics:
Mean Absolute Error (MAE) using sklearn: 0.4600000000000016
Mean Squared Error (MSE) using sklearn: 0.24600000000000147
Root Mean Squared Error (RMSE) using sklearn: 0.49598387070549127
R-squared (R²) using sklearn: 0.99877


Question 2 :(1 ponto) Write python code from scratch to find evaluation metrics of deep learning model.
Actual values and deep learning model predicted values are shown in Table 2. Also compare the
results with outcome of libraries
YActual YP red
0 0 1 1 2 0
0 0 1 0 2 0
0 1 1 2 2 1
0 2 1 0 2 2
0 2 1 2 2 2
Tabela 2: YActual Vs. YP red
• Expected Leaning Outcomes from this assignment related to python
– Students are able to understand deep learning model metrics
– Students are able to write code in python to find deep learning model metrics
– Students are able to use python libraries to find deep learning model metrics
• Naming cinvention

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
YActual = np.array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
YPred = np.array([0, 1, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2])
accuracy = np.sum(YActual == YPred) / len(YActual)
precision = {}
recall = {}
f1 = {}
classes = np.unique(YActual)

for cls in classes:
    tp = np.sum((YActual == cls) & (YPred == cls))
    fp = np.sum((YActual != cls) & (YPred == cls))
    fn = np.sum((YActual == cls) & (YPred != cls))
    tn = np.sum((YActual != cls) & (YPred != cls))

    precision[cls] = tp / (tp + fp) if (tp + fp) != 0 else 0
    recall[cls] = tp / (tp + fn) if (tp + fn) != 0 else 0
    f1[cls] = 2 * (precision[cls] * recall[cls]) / (precision[cls] + recall[cls]) if (precision[cls] + recall[cls]) != 0 else 0
conf_matrix = confusion_matrix(YActual, YPred)
print(f"Manual Error Metrics:")
print(f"Accuracy: {accuracy}")
for cls in classes:
    print(f"Class {cls}: Precision = {precision[cls]}, Recall = {recall[cls]}, F1-Score = {f1[cls]}")
print(f"Confusion Matrix:\n{conf_matrix}")

Manual Error Metrics:
Accuracy: 0.3333333333333333
Class 0: Precision = 0.4, Recall = 0.5, F1-Score = 0.4444444444444445
Class 1: Precision = 0.3333333333333333, Recall = 0.25, F1-Score = 0.28571428571428575
Class 2: Precision = 0.25, Recall = 0.25, F1-Score = 0.25
Confusion Matrix:
[[2 1 1]
 [1 1 2]
 [2 1 1]]


In [ ]:
accuracy_sklearn = accuracy_score(YActual, YPred)
precision_sklearn = precision_score(YActual, YPred, average=None, labels=np.unique(YActual))
recall_sklearn = recall_score(YActual, YPred, average=None, labels=np.unique(YActual))
f1_sklearn = f1_score(YActual, YPred, average=None, labels=np.unique(YActual))
conf_matrix_sklearn = confusion_matrix(YActual, YPred)
print("\nSklearn Error Metrics:")
print(f"Accuracy using sklearn: {accuracy_sklearn}")
print(f"Precision using sklearn: {precision_sklearn}")
print(f"Recall using sklearn: {recall_sklearn}")
print(f"F1-Score using sklearn: {f1_sklearn}")
print(f"Confusion Matrix using sklearn:\n{conf_matrix_sklearn}")


Sklearn Error Metrics:
Accuracy using sklearn: 0.3333333333333333
Precision using sklearn: [0.4        0.33333333 0.25      ]
Recall using sklearn: [0.5  0.25 0.25]
F1-Score using sklearn: [0.44444444 0.28571429 0.25      ]
Confusion Matrix using sklearn:
[[2 1 1]
 [1 1 2]
 [2 1 1]]
